window.CASE_PDFS = {
  "1.1 Hypertension": "assets/pdfs/Medicine/Cardiology/1.1_Hypertension.pdf",
  "1.2 Chest Pain (SDL)": "assets/pdfs/Medicine/Cardiology/1.2_Chest Pain [SDL].pdf",
  "1.3 Heart Failure": "assets/pdfs/Medicine/Cardiology/1.3_Heart Failure.pdf",
  "1.4 Hyperlipidaemia (Acquired)": "assets/pdfs/Medicine/Cardiology/1.4_Hyperlipidaemia (Acquired).pdf",
  "1.5 Obesity": "assets/pdfs/Medicine/Cardiology/1.5_Obesity.pdf",
  "1.6 Smoking Cessation (SDL)": "assets/pdfs/Medicine/Cardiology/1.6_Smoking Cessation [SDL].pdf",
  "2.2 Cardiomyopathy (Dilated) [SDL]": "assets/pdfs/Medicine/Cardiology/2.2_Cardiomyopathy (Dilated) [SDL].pdf",
  "2.3 Stable Angina": "assets/pdfs/Medicine/Cardiology/2.3_Stable Angina.pdf",
  "2.4 Unstable Angina": "assets/pdfs/Medicine/Cardiology/2.4_Unstable Angina.pdf",
  "2.5 Myocardial Infarction": "assets/pdfs/Medicine/Cardiology/2.5_Myocardial Infarction.pdf",
  "2.6 Hyperlipidaemia (Congenital) [SDL]": "assets/pdfs/Medicine/Cardiology/2.6_Hyperlipidaemia (Congenital) [SLD].pdf",
  "3.1 Peri-Operative Management": "assets/pdfs/Surgery/General/3.1_Peri-Operative Management.pdf",
  "3.2 Appendicitis": "assets/pdfs/Surgery/General/3.2_Appendicitis.pdf",
  "3.3 Surgical Wound Management [SDL]": "assets/pdfs/Surgery/General/3.3_Surgical Wound Management [SDL].pdf",
  "3.4 Post Operative Fever [SDL]": "assets/pdfs/Surgery/General/3.4_Post Operative Fever [SDL].pdf",
  "3.5 Pancreatitis": "assets/pdfs/Surgery/General/3.5_Pancreatitis.pdf",
  "3.6 Cholecystitis & Biliary Colic": "assets/pdfs/Surgery/General/3.6_Cholecystitis & Biliary Colic.pdf",
  "3.7 Choledocolethiasis & Cholecystectomy [SDL]": "assets/pdfs/Surgery/General/3.7_Choledocolethiasis & Cholecystectomy [SDL].pdf",
  "4.1 Pre-Conception Care": "assets/pdfs/Medicine/O&G/4.1_Pre-Conception Care.pdf",
  "4.2 Antenatal Care": "assets/pdfs/Medicine/O&G/4.2_Antenatal Care.pdf",
  "4.3 Bleeding in Early Pregnancy": "assets/pdfs/Medicine/O&G/4.3_Bleeding in Early Pregnancy.pdf",
  "4.4 Ectopic Pregnancy": "assets/pdfs/Medicine/O&G/4.4_Ectopic Pregnancy.pdf",
  "4.5 Vulvovaginitis (Adolescence) [SDL]": "assets/pdfs/Medicine/O&G/4.5_Vulvovaginitis (Adolescence) [SDL].pdf",
  "4.6 Dysmenorrhea & Menorrhagia (Adolescence)": "assets/pdfs/Medicine/O&G/4.6_Dysmenorrhea & Menorrhagia (Adolescence).pdf",
  "4.7 Contraception (Adolescence)": "assets/pdfs/Medicine/O&G/4.7_Contraception (Adolescence).pdf",
  "5.1 Self Harm & Suicide [SDL]": "assets/pdfs/Medicine/Psychiatry/5.1_Self Harm & Suicide [SDL].pdf",
  "5.2 Anxiety Disorders": "assets/pdfs/Medicine/Psychiatry/5.2_Anxiety Disorders.pdf",
  "5.3 Depression": "assets/pdfs/Medicine/Psychiatry/5.3_Depression.pdf",
  "5.4 Bipolar Disorder": "assets/pdfs/Medicine/Psychiatry/5.4_Bipolar Disorder.pdf",
  "5.5 (from screenshot)": null,
  "5.6 (from screenshot)": null,
  "6.1 T1D (New Diagnosis)": "assets/pdfs/Medicine/Paediatrics/6.1_T1D (new diagnosis).pdf",
  "6.2 T1D (Ongoing Management)": "assets/pdfs/Medicine/Paediatrics/6.2_T1D (Ongoing management).pdf",
  "6.3 Cystic Fibrosis": "assets/pdfs/Medicine/Paediatrics/6.3_Cystic Fibrosis (meconium ileus).pdf",
  "6.4 Growth (Short Stature)": "assets/pdfs/Medicine/Paediatrics/6.4_Growth (Short Stature).pdf",
  "7.1 Asthma Exacerbation": "assets/pdfs/Medicine/Respiratory/7.1_Asthma Exacerbation.pdf",
  "7.2 Severe Asthma": "assets/pdfs/Medicine/Respiratory/7.2_Severe Asthma.pdf",
  "7.3 COPD": "assets/pdfs/Medicine/Respiratory/7.3_COPD.pdf",
  "7.4 Bronchiectasis [SDL]": "assets/pdfs/Medicine/Respiratory/7.4_Bronchiectasis [SDL].pdf",
  "7.5 Cystic Fibrosis [SDL]": "assets/pdfs/Medicine/Respiratory/7.5_Cystic Fibrosis [SDL].pdf",
  "7.6 Community Acquired Pneumonia": "assets/pdfs/Medicine/Respiratory/7.6_Community Acquired Pneumonia.pdf",
  "8.1 Diverticular Disease": "assets/pdfs/Surgery/GIT/8.1_Diverticular DIsease.pdf",
  "8.2 Colorectal Polyps & Cancer": "assets/pdfs/Surgery/GIT/8.2_Colorectal Polyps & Cancer.pdf",
  "8.3 IBD (UC & Chrons)": "assets/pdfs/Surgery/GIT/8.3_IBD (UC & Chrons).pdf",
  "8.4 LBO [SDL]": "assets/pdfs/Surgery/GIT/8.4_LBO [SDL].pdf",
  "8.5 Internal & External Haemorrhoids": "assets/pdfs/Surgery/GIT/8.5_Internal & External Haemorrhoids.pdf",
  "8.6 Perianal Access & Fistula": "assets/pdfs/Surgery/GIT/8.6_Perianal Access & Fistula.pdf",
  "8.7 Anal Fissures, Cancers and STIs [SDL]": "assets/pdfs/Surgery/GIT/8.7_Anal Fissures, Cancers and STIs [SDL].pdf",
  "9.1 Asthma (ED)": "assets/pdfs/Medicine/Paediatrics/9.1_Asthma (ED).pdf",
  "9.2 Poisoning & Envenomation": "assets/pdfs/Medicine/Paediatrics/9.2_Poisoning & Envenomation.pdf",
  "9.3 DDH": "assets/pdfs/Medicine/Paediatrics/9.3_DDH (Developmental Dysplasia of Hip).pdf",
  "9.4 Common Surgical Conditions in Kids": null,
  "9.6 Neonatal Resuscitation": "assets/pdfs/Medicine/O&G/13.4_Prematurity & Neonatal Resusitation.pdf",
  "9.7 Infections at Birth": "assets/pdfs/Medicine/Paediatrics/9.7_Infections at Birth.pdf",
  "10.1 Obstructive Sleep Apnoea": "assets/pdfs/Medicine/Respiratory/10.1_Obstructive Sleep Apnoea.pdf",
  "10.2 Pneumonia [SDL]": "assets/pdfs/Medicine/Respiratory/10.2_Pneumonia [SDL].pdf",
  "10.3 Tuberculosis [SDL]": "assets/pdfs/Medicine/Respiratory/10.3_Tuberculosis [SDL].pdf",
  "10.4 Bronchial Cancer": "assets/pdfs/Medicine/Respiratory/10.4_Bronchial Cancer.pdf",
  "10.5 Interstitial Lung Disease & Sarcoidosis": "assets/pdfs/Medicine/Respiratory/10.5_Interstitial Lung Disease & Sarcoidosis.pdf",
  "10.6 Pulmonary Embolism": "assets/pdfs/Medicine/Respiratory/10.6_Pulmonary Embolism.pdf",
  "11.1 Inguinal Hernias": "assets/pdfs/Surgery/General/11.1_Inguinal Hernias.pdf",
  "11.2 Umbilical Hernias": "assets/pdfs/Surgery/General/11.2_Umbilical Hernias.pdf",
  "11.3 Breast Cancers [SDL]": "assets/pdfs/Surgery/Breast & Endocrine/11.3_Breast Cancers [SDL].pdf",
  "11.4 Benign Breast Conditions": "assets/pdfs/Surgery/Breast & Endocrine/11.4_Benign Breast Conditions.pdf",
  "11.5 Breast Cancer (new diagnosis)": "assets/pdfs/Surgery/Breast & Endocrine/11.5_Breast Cancer (new diagnosis).pdf",
  "11.6 Breast Cancer (Terminal)": "assets/pdfs/Surgery/Breast & Endocrine/11.6_Breast Cancer (Terminal).pdf",
  "11.7 Electrolyte Management [SDL]": "assets/pdfs/Surgery/General/11.7_Electrolyte Management [SDL].pdf",
  "12.1 Febrile Seizures": "assets/pdfs/Medicine/Paediatrics/12.1_Febrile Seizures.pdf",
  "12.2 Afebrile Seizures (Epilepsy)": "assets/pdfs/Medicine/Paediatrics/12.2_Afebrile Seizures (epilepsy).pdf",
  "12.3 Headache (Migraine)": "assets/pdfs/Medicine/Paediatrics/12.3_Headache (Migraine).pdf",
  "12.4 Hydrocephalus": "assets/pdfs/Medicine/Paediatrics/12.4_Hydrocephalus (big head).pdf",
  "12.5 Neural Tube Defects": "assets/pdfs/Medicine/Paediatrics/12.5_Neural Tube Defects (myelomeningocele).pdf",
  "12.6 Developmental Delay (Cerebral Palsy)": "assets/pdfs/Medicine/Paediatrics/12.6_Developmental Delay (Cerebral Palsy).pdf",
  "13.1 Normal Vs Abnormal Labour": "assets/pdfs/Medicine/O&G/13.1_Normal Vs Abnormal Labour.pdf",
  "13.2 Labour (Obstetric Emergencies)": "assets/pdfs/Medicine/O&G/13.2_Labour (Obstetric Emergencies).pdf",
  "13.3 Analgesia in Birth & Cesarian": "assets/pdfs/Medicine/O&G/13.3_Analgesia in Birth & Cesarian.pdf",
  "13.4 Prematurity & Neonatal Resusitation": "assets/pdfs/Medicine/O&G/13.4_Prematurity & Neonatal Resusitation.pdf",
  "14.1 UTI": "assets/pdfs/Medicine/Renal/14.1_UTI.pdf",
  "14.2 Renal Calculi": "assets/pdfs/Medicine/Renal/14.2_Renal Calculi.pdf",
  "14.3 Nephrotic Syndrome (Glomerulonephritis)": "assets/pdfs/Medicine/Renal/14.3_Nephrotic Syndrome (Glomerulonephritis).pdf",
  "14.4 Diabetic Nephropathy [SDL]": "assets/pdfs/Medicine/Renal/14.4_Diabetic Nephropathy [SDL].pdf",
  "14.5 Haematuria [SDL]": "assets/pdfs/Medicine/Renal/14.5_Haematuria [SDL].pdf",
  "14.6 Prostate Cancer": "assets/pdfs/Medicine/Renal/14.6_Prostate Cancer.pdf",
  "15.1 Self Harm & Suicide [SDL]": "assets/pdfs/Medicine/Psychiatry/5.1_Self Harm & Suicide [SDL].pdf",
  "15.2 Anxiety Disorders": "assets/pdfs/Medicine/Psychiatry/5.2_Anxiety Disorders.pdf",
  "15.3 Depression": "assets/pdfs/Medicine/Psychiatry/5.3_Depression.pdf",
  "15.4 Bipolar Disorder": "assets/pdfs/Medicine/Psychiatry/5.4_Bipolar Disorder.pdf",
  "15.5 Personality Disorders": "assets/pdfs/Medicine/Psychiatry/15.5_Personality Disorders.pdf",
  "15.6 (from screenshot)": null,
  "16.1 Noonan Syndrome": "assets/pdfs/Medicine/Paediatrics/16.1_Noonan Syndrome.pdf",
  "16.2 Pyloric Stenosis": "assets/pdfs/Medicine/Paediatrics/16.2_Pyloric Stenosis.pdf",
  "16.3 Acute Diarrhoea": "assets/pdfs/Medicine/Paediatrics/16.3_Acute Diarrhoea.pdf",
  "16.4 Chronic Diarrhoea & Malabsorption": "assets/pdfs/Medicine/Paediatrics/16.4_Chronic Diarrhoea & Malabsorption.pdf",
  "16.5 Febrile Child & Vaccination": "assets/pdfs/Medicine/Paediatrics/16.5_Febrile Child & Vaccination.pdf",
  "16.6 Teething [SDL]": "assets/pdfs/Medicine/Paediatrics/16.6_Teething [SDL].pdf",
  "17.1 Primary Hypothyroidism": "assets/pdfs/Medicine/Endocrinology/17.1_Primary Hypothyroidism.pdf",
  "17.2 Graves Disease": "assets/pdfs/Medicine/Endocrinology/17.2_Graves Disease.pdf",
  "17.3 Thyroid Mass [SDL]": "assets/pdfs/Medicine/Endocrinology/17.3_Thyroid Mass [SDL].pdf",
  "17.4 Cushing's Disease [SDL]": "assets/pdfs/Medicine/Endocrinology/17.4_Cushing\u2019s Disease [SDL].pdf",
  "17.5 Adrenal Insufficiency": "assets/pdfs/Medicine/Endocrinology/17.5_Adrenal Insufficiency.pdf",
  "17.6 Calcium Metabolism Disorders": "assets/pdfs/Medicine/Endocrinology/17.6_Calcium Metabolism Disorders.pdf",
  "18.1 Menorrhagia": "assets/pdfs/Medicine/O&G/18.1_Menorrhagia.pdf",
  "18.2 Post-Menopausal Bleeding": "assets/pdfs/Medicine/O&G/18.2_Post-Menopausal Bleeding.pdf",
  "18.3 Acute Pelvic Pain (Benign Ovarian Disease)": "assets/pdfs/Medicine/O&G/18.3_Acute Pelvic Pain (Benign Ovarian Disease).pdf",
  "18.4 Endometriosis": "assets/pdfs/Medicine/O&G/18.4_Endometriosis.pdf",
  "18.5 Premalignant Disease of the Cervix": "assets/pdfs/Medicine/O&G/18.5_Premalignant Disease of the Cervix.pdf",
  "19.1 Osteoarthritis": "assets/pdfs/Surgery/Ortho/19.1_Osteoarthritis.pdf",
  "19.2 Septic Arthritis": "assets/pdfs/Surgery/Ortho/19.2_Septic Arthritis.pdf",
  "19.3 Bony Lumps": "assets/pdfs/Surgery/Ortho/19.3_Bony Lumps.pdf",
  "19.4 Gout": "assets/pdfs/Surgery/Ortho/19.4_Gout.pdf",
  "19.5 Knee Injuries": "assets/pdfs/Surgery/Ortho/19.5_Knee Injuries.pdf",
  "19.6 Paediatric Fractures": "assets/pdfs/Surgery/Ortho/19.6_Paediatric Fractures.pdf",
  "20.1 Child with Cough": "assets/pdfs/Medicine/Paediatrics/20.1_Child with Cough.pdf",
  "20.2 Child with Wheeze": "assets/pdfs/Medicine/Paediatrics/20.2_Child with Wheeze.pdf",
  "20.3 The Atopic Child": "assets/pdfs/Medicine/Paediatrics/20.3_The Atopic Child.pdf",
  "20.4 Asthma (Acute Exacerbation)": "assets/pdfs/Medicine/Paediatrics/20.4_Asthma (Acute Exacerbation).pdf",
  "20.5 Child with Stridor": "assets/pdfs/Medicine/Paediatrics/20.5_Child with Stridor.pdf",
  "20.6 Pneumonia": "assets/pdfs/Medicine/Paediatrics/20.6_Pneumonia.pdf",
  "21.1 Oesophageal Carcinoma": "assets/pdfs/Medicine/Gastroenterology/21.1_Oesophageal Carcinoma.pdf",
  "21.2 Gastric Ulcers & Gastric Cancer": "assets/pdfs/Medicine/Gastroenterology/21.2_Gastric Ulcers & Gastric Cancer.pdf",
  "21.3 Coeliac [SDL]": "assets/pdfs/Medicine/Gastroenterology/21.3_Coeliac [SDL].pdf",
  "21.4 Constipation [SDL]": "assets/pdfs/Medicine/Gastroenterology/21.4_Constipation [SDL].pdf",
  "21.5 IBS": "assets/pdfs/Medicine/Gastroenterology/21.5_IBS.pdf",
  "22.1 Stroke & TIA": "assets/pdfs/Medicine/Neurology/22.1_Stroke & TIA.pdf",
  "22.2 Multiple Sclerosis": "assets/pdfs/Medicine/Neurology/22.2_Multiple Sclerosis.pdf",
  "22.3 Alzheimers": "assets/pdfs/Medicine/Neurology/22.3_Alzheimers.pdf",
  "22.4 Parkinsons & MND": "assets/pdfs/Medicine/Neurology/22.4_Parkinsons & MND.pdf",
  "22.5 Meningitis [SDL]": "assets/pdfs/Medicine/Neurology/22.5_Meningitis [SDL].pdf",
  "22.6 Creutzfeldt-Jacob Disease [SDL]": "assets/pdfs/Medicine/Neurology/22.6_Creutzfeldt-Jacob Disease [SDL].pdf",
  "22.7 Intracranial Tumours & Hydrocephalus [SDL]": "assets/pdfs/Medicine/Neurology/22.7_Intracranial Tumours & Hydrocephalus [SDL].pdf",
  "23.1 Congenital Heart Disease (Acyanotic)": "assets/pdfs/Medicine/Paediatrics/23.1_Congenital Heart Disease (Acyanotic).pdf",
  "23.2 Congenital Heart Disease (Cyanotic)": "assets/pdfs/Medicine/Paediatrics/23.2_Congenital Heart Disease (Cyanotic).pdf",
  "23.3 Nasolacrimal Duct Blockage": "assets/pdfs/Medicine/Paediatrics/23.3_Nasolacrimal Duct Blockage.pdf",
  "23.4 Strabismus": "assets/pdfs/Medicine/Paediatrics/23.4_Strabismus.pdf",
  "23.5 Laryngomalacia": "assets/pdfs/Medicine/Paediatrics/23.5_LAryngomalacia (infant w Stridor).pdf",
  "24.2 Secondary Amenorrhoea": "assets/pdfs/Medicine/O&G/24.2_Secondary Amenorrhoea.pdf",
  "24.3 PCOS": "assets/pdfs/Medicine/O&G/24.3_PCOS.pdf",
  "24.4 Infertility": "assets/pdfs/Medicine/O&G/24.4_Infertility.pdf",
  "24.5 Primary Amenorrhoea [SDL]": "assets/pdfs/Medicine/O&G/24.5_Primary Amenorrhoea [SDL].pdf",
  "24.6 Hirsutism [SDL]": "assets/pdfs/Medicine/O&G/24.6_Hirsutism [SDL].pdf",
  "24.7 Pre-Menstrual Syndrome & Dysphoric Disorder": "assets/pdfs/Medicine/O&G/24.7_Pre-Menstrual Syndrome & Dysphoric Disorder.pdf",
  "25.1 Self Harm & Suicide [SDL]": "assets/pdfs/Medicine/Psychiatry/5.1_Self Harm & Suicide [SDL].pdf",
  "25.2 Anxiety Disorders": "assets/pdfs/Medicine/Psychiatry/5.2_Anxiety Disorders.pdf",
  "25.3 Depression": "assets/pdfs/Medicine/Psychiatry/5.3_Depression.pdf",
  "25.4 Bipolar Disorder": "assets/pdfs/Medicine/Psychiatry/5.4_Bipolar Disorder.pdf",
  "25.5 (from screenshot)": null,
  "25.6 (from screenshot)": null,
  "26.1 Rheumatoid Arthritis": "assets/pdfs/Medicine/Rheumatology/26.1_Rheumatoid Arthritis.pdf",
  "26.2 Ankylosing Spondylitis": "assets/pdfs/Medicine/Rheumatology/26.2_Ankylosing Spondylitis.pdf",
  "26.3 Polymyalgia Rheumatica & Temporal Arteritis": "assets/pdfs/Medicine/Rheumatology/26.3_Polymyalgia Rheumatica & Temporal Arteritis.pdf",
  "26.4 Fibromyalgia [SDL]": "assets/pdfs/Medicine/Rheumatology/26.4_Fibromyalgia [SDL].pdf",
  "26.5 Osteoporosis": "assets/pdfs/Medicine/Rheumatology/26.5_Osteoperosis.pdf",
  "26.6 Paget\u2019s Disease (bone)": "assets/pdfs/Medicine/Rheumatology/26.6_Paget\u2019s Disease (bone).pdf",
  "27.1 Asthma Exacerbation": "assets/pdfs/Medicine/Respiratory/7.1_Asthma Exacerbation.pdf",
  "27.2 Severe Asthma": "assets/pdfs/Medicine/Respiratory/7.2_Severe Asthma.pdf",
  "27.3 COPD": "assets/pdfs/Medicine/Respiratory/7.3_COPD.pdf",
  "27.4 Bronchiectasis [SDL]": "assets/pdfs/Medicine/Respiratory/7.4_Bronchiectasis [SDL].pdf",
  "27.5 Cystic Fibrosis [SDL]": "assets/pdfs/Medicine/Respiratory/7.5_Cystic Fibrosis [SDL].pdf",
  "27.6 Community Acquired Pneumonia": "assets/pdfs/Medicine/Respiratory/7.6_Community Acquired Pneumonia.pdf",
  "28.1 UTI": "assets/pdfs/Medicine/Paediatrics/28.1_UTI.pdf",
  "28.2 Glomerulonephritis": "assets/pdfs/Medicine/Renal/14.3_Nephrotic Syndrome (Glomerulonephritis).pdf",
  "28.3 Nephrotic Syndrome": "assets/pdfs/Medicine/Paediatrics/28.3_Nephrotic Syndrome.pdf",
  "28.4 Anaemia (Nutritional)": "assets/pdfs/Medicine/Paediatrics/28.4_Anaemia (nutritional).pdf",
  "28.5 Purpuric Rash": "assets/pdfs/Medicine/Paediatrics/28.5_Purpuric Rash.pdf",
  "28.6 Acute Lymphoblastic Leukaemia": "assets/pdfs/Medicine/Paediatrics/28.6_Acute Lymphoblastic Leukaemia.pdf",
  "29.1 Urinary Stress Incontinence": "assets/pdfs/Medicine/O&G/29.1_Urinary Stress Incontinence.pdf",
  "29.2 Urinary Urge Incontinence": "assets/pdfs/Medicine/O&G/29.2_Urinary Urge Incontinence.pdf",
  "29.3 Uterine Prolapse": "assets/pdfs/Medicine/O&G/29.3_Uterine Prolapse.pdf",
  "29.4 Perimenopause & Menopause": "assets/pdfs/Medicine/O&G/29.4_Perimenopause & Menopause.pdf",
  "29.5 Menopause": "assets/pdfs/Medicine/O&G/29.5_Menopause.pdf",
  "29.6 Candidiasis [SDL]": "assets/pdfs/Medicine/O&G/29.6_Candidiasis [SDL].pdf",
  "29.7 Genital Herpes [SDL]": "assets/pdfs/Medicine/O&G/29.7_Genital Herpes [SDL].pdf",
  "29.8 Unplanned Pregnancy [SDL]": "assets/pdfs/Medicine/O&G/29.8_Unplanned Pregnancy [SDL].pdf",
  "30.1 Microcytic Anaemia": "assets/pdfs/Medicine/Haematology/30.1_Microcytic Anaemia.pdf",
  "30.2 Macrocytic Anaemia": "assets/pdfs/Medicine/Haematology/30.2_Macrocytic Anaemia.pdf",
  "30.3 Aplastic Anaemia [SDL]": "assets/pdfs/Medicine/Haematology/30.3_Aplastic Anaemia [SDL].pdf",
  "30.4 Haemolytic Anaemia [SDL]": "assets/pdfs/Medicine/Haematology/30.4_Haemolytic Anaemia [SDL].pdf",
  "30.5 Myelofibrosis": "assets/pdfs/Medicine/Haematology/30.5_Myelofibrosis.pdf",
  "30.6 Thrombocytopaenia": "assets/pdfs/Medicine/Haematology/30.6_Thrombocytopaenia.pdf",
  "30.3 Aplastic Anaemia (SDL)": "assets/pdfs/Medicine/Haematology/30.3_Aplastic Anaemia [SDL].pdf",
  "30.4 Haemolytic Anaemia (SDL)": "assets/pdfs/Medicine/Haematology/30.4_Haemolytic Anaemia [SDL].pdf"
};
